[package]
name = "pku-guide"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"
minifb = "0.25"
reqwest = { version = "0.11", features = ["blocking", "json"] }  
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }  
colored = "2.0" 
rand = "0.8"